version: "2"

services:
  zookeeper:
    image: zookeeper:3.5.9
    ports:
      - 2181:2181
  kafka-broker:
    image: debezium/kafka:1.5
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: mysql:5.6.50
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=xudjf23adj213
      - MYSQL_USER=apollo
      - MYSQL_PASSWORD=apollo-passwd
#    volumes:
#      - ./.data/mysql:/var/lib/mysql
  clickhouse-server:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123 # http interface
      - 9000:9000 # native client
#    volumes:
#      - ./.data/clickhouse:/var/lib/clickhouse
