spring:
  application:
    name: apollo-marketing
  profiles:
    include:
      - mysql
      - clickhouse
  kafka:
    producer:
      acks: all
      retries: 3
      properties:
        enable:
          idempotence: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  jackson:
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
    parser:
      IGNORE_UNDEFINED: true
logging:
  group:
    apollo: com.doutiaotech.apollo
  level:
    root: info
    sql: debug
    web: debug
    apollo: debug

  file:
    path: ./.logs