spring:
  application:
    name: apollo-marketing
  kafka:
    producer:
      acks: all
      retries: 3
      properties:
        enable:
          idempotence: true
      bootstrap-servers: localhost:19092
      transaction-id-prefix: tx-
    consumer:
      bootstrap-servers: localhost:19092
      enable-auto-commit: false
      fetch-max-wait: 1000
      auto-offset-reset: earliest
      fetch-min-size: 512KB
      isolation-level: read_committed
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  jackson:
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
    parser:
      IGNORE_UNDEFINED: true
  task:
    scheduling:
      pool:
        size: 2
      shutdown:
        await-termination: true

server:
  port: 8888

mysql:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/apollo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: apollo
    password: apollo-passwd
clickhouse:
  datasource:
    jdbcUrl: jdbc:clickhouse://localhost:8123/apollo
    driverClassName: ru.yandex.clickhouse.ClickHouseDriver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    map-underscore-to-camel-case: true

feign:
  client:
    config:
      default:
        loggerLevel: BASIC

syncer:
  trade:
    corePoolSize: 10
    maxPoolSize: 10
    keepAliveSeconds: 60
    queueCapacity: 100
    allowCoreThreadTimeOut: true
    threadNamePrefixSet: true
