spring:
  application:
    name: apollo-marketing
logging:
  group:
    apollo: com.doutiaotech.apollo
  level:
    root: info
    sql: debug
    web: debug
    apollo: debug

  file:
    path: ./.logs
