mysql:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/apollo
    driverClassName: com.mysql.jdbc.Driver
    username: apollo
    password: apollo-passwd
    type: com.zaxxer.hikari.HikariDataSource

clickhouse:
  datasource:
    jdbcUrl: jdbc:clickhouse://localhost:8123/apollo
    driverClassName: ru.yandex.clickhouse.ClickHouseDriver
