name: Example workflow for Codecov
on:
  pull_request:
  push:
    paths:
      - '**/src/**'
      - '**/pom.xml'
    branches:
      - master
      - development
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache mvn dependencies
        uses: actions/cache@v2.1.5
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ env.cache-name }}-
      - name: Test and Generate coverage report
        run: mvn -B test --file pom.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: >
            ./api-syncer/target/site/jacoco/jacoco.xml,
            ./apollo-util/target/site/jacoco/jacoco.xml
          flags: unittests
          verbose: true