# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to Server

on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'pom version'
        required: true
        default: '1.0-SNAPSHOT'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache mvn dependencies
        uses: actions/cache@v2.1.5
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ env.cache-name }}-
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Drevision=${{github.event.inputs.revision}}
      - name: SCP Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{secrets.PASSPHRASE}}
          source: "starter/target/starter-${{github.event.inputs.revision}}.jar"
          target: "~"
          strip_components: 2
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{secrets.PASSPHRASE}}
          script: |
            [[ -f /etc/init.d/apollo ]] && sudo /etc/init.d/apollo stop
            [[ -f ~/apollo.jar ]] && mv ~/apollo.jar ~/apollo-old.jar
            mv ~/starter-${{github.event.inputs.revision}}.jar ~/apollo.jar
            [[ -f /etc/init.d/apollo ]] && sudo rm -rf /etc/init.d/apollo
            sudo ln -s -f ~/apollo.jar /etc/init.d/apollo
            sudo /etc/init.d/apollo start
            [[ -f ~/apollo.jar ]] && rm ~/apollo-old.jar
