# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish web api to repository

on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'pom version'
        required: true
        default: '1.0-SNAPSHOT'
      message:
        description: 'commit message'
        required: true
        default: 'update openapi.yaml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache mvn dependencies
        uses: actions/cache@v2.1.5
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ env.cache-name }}-

      - name: Verify project and generate openapi.yaml
        run: mvn -B verify --file pom.xml -Drevision=${{github.event.inputs.revision}}

      - name: Upload to GitHub
        uses: LasyIsLazy/github-upload-action@v0.0.2
        with:
          access-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          file-path: ./starter/target/openapi.yaml
          username: DouTiao-Tech
          repo: apollo-marketing-api
          commit-message: ${{github.event.inputs.message}}
